-- DMA rm_services (large table). Loaded with dma_radius_tables*.sql

###
CREATE TABLE IF NOT EXISTS rm_services (
  srvid INTEGER NOT NULL PRIMARY KEY,
  srvname VARCHAR(50) NOT NULL,
  descr VARCHAR(255) NOT NULL,
  downrate INTEGER NOT NULL,
  uprate INTEGER NOT NULL,
  limitdl SMALLINT NOT NULL,
  limitul SMALLINT NOT NULL,
  limitcomb SMALLINT NOT NULL,
  limitexpiration SMALLINT NOT NULL,
  limituptime SMALLINT NOT NULL,
  poolname VARCHAR(50) NOT NULL,
  unitprice NUMERIC(25,6) NOT NULL,
  unitpriceadd NUMERIC(25,6) NOT NULL,
  timebaseexp SMALLINT NOT NULL,
  timebaseonline SMALLINT NOT NULL,
  timeunitexp INTEGER NOT NULL,
  timeunitonline INTEGER NOT NULL,
  trafficunitdl INTEGER NOT NULL,
  trafficunitul INTEGER NOT NULL,
  trafficunitcomb INTEGER NOT NULL,
  inittimeexp INTEGER NOT NULL,
  inittimeonline INTEGER NOT NULL,
  initdl INTEGER NOT NULL,
  initul INTEGER NOT NULL,
  inittotal INTEGER NOT NULL,
  srvtype SMALLINT NOT NULL,
  timeaddmodeexp SMALLINT NOT NULL,
  timeaddmodeonline SMALLINT NOT NULL,
  trafficaddmode SMALLINT NOT NULL,
  monthly SMALLINT NOT NULL,
  enaddcredits SMALLINT NOT NULL,
  minamount BIGINT NOT NULL,
  minamountadd BIGINT NOT NULL,
  resetcounters SMALLINT NOT NULL,
  pricecalcdownload SMALLINT NOT NULL,
  pricecalcupload SMALLINT NOT NULL,
  pricecalcuptime SMALLINT NOT NULL,
  unitpricetax NUMERIC(25,6) NOT NULL,
  unitpriceaddtax NUMERIC(25,6) NOT NULL,
  enableburst SMALLINT NOT NULL,
  dlburstlimit INTEGER NOT NULL,
  ulburstlimit INTEGER NOT NULL,
  dlburstthreshold INTEGER NOT NULL,
  ulburstthreshold INTEGER NOT NULL,
  dlbursttime INTEGER NOT NULL,
  ulbursttime INTEGER NOT NULL,
  enableservice INTEGER NOT NULL,
  dlquota BIGINT NOT NULL,
  ulquota BIGINT NOT NULL,
  combquota BIGINT NOT NULL,
  timequota BIGINT NOT NULL,
  priority SMALLINT NOT NULL,
  nextsrvid INTEGER NOT NULL,
  dailynextsrvid INTEGER NOT NULL,
  disnextsrvid INTEGER NOT NULL,
  availucp SMALLINT NOT NULL,
  renew SMALLINT NOT NULL,
  carryover SMALLINT NOT NULL,
  policymapdl VARCHAR(50) NOT NULL,
  policymapul VARCHAR(50) NOT NULL,
  custattr VARCHAR(255) NOT NULL,
  gentftp SMALLINT NOT NULL,
  cmcfg TEXT NOT NULL DEFAULT '',
  advcmcfg SMALLINT NOT NULL,
  addamount INTEGER NOT NULL,
  ignstatip SMALLINT NOT NULL
);

###
CREATE INDEX IF NOT EXISTS rm_services_srvname ON rm_services (srvname);
